//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEstagio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataContratacao { get; set; }
        public Nullable<System.DateTime> DataExeculcao { get; set; }
    }
}
